build:
    image: default-bionic
    environment:
        php: 8.1.0
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
filter:
    paths: ["src/*"]
